package com.example.wanandroid.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.wanandroid.data.entity.Wechat;

import com.example.wanandroid.greendaodemo.db.WechatDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wechatDaoConfig;

    private final WechatDao wechatDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wechatDaoConfig = daoConfigMap.get(WechatDao.class).clone();
        wechatDaoConfig.initIdentityScope(type);

        wechatDao = new WechatDao(wechatDaoConfig, this);

        registerDao(Wechat.class, wechatDao);
    }
    
    public void clear() {
        wechatDaoConfig.clearIdentityScope();
    }

    public WechatDao getWechatDao() {
        return wechatDao;
    }

}
